name: "Comment on a Pull Request"

inputs:
  body:
    description: "Comment body"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          if(!context.payload.pull_request) return
          const prNumber = context.payload.pull_request.number
          const commitSha = context.payload.pull_request.head.sha
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber
          })
          const {
            data: {
              head: { ref: branch }
            }
          } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          })
          const botComment = comments.find((comment) => comment.user.login === 'github-actions[bot]')
          const body = `${{ inputs.body }}`
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body
            })
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            })
          }
